# DocGen CLI Workflow Configuration
# Automated workflow management and task execution

# Daily Tasks
daily_tasks:
  - check_project_health
  - run_tests
  - update_documentation
  - validate_specs

# Weekly Tasks
weekly_tasks:
  - comprehensive_qa
  - performance_analysis
  - security_audit
  - dependency_update
  - code_review
  - documentation_review

# Monthly Tasks
monthly_tasks:
  - architecture_review
  - dependency_audit
  - security_scan
  - performance_benchmark
  - user_feedback_review

# Quality Gates
quality_gates:
  test_coverage: 80
  performance_threshold: 5  # seconds for document generation
  security_score: 90
  code_quality_score: 85
  documentation_coverage: 90

# Workflow Settings
workflow:
  # Execution settings
  parallel_execution: true
  max_retries: 3
  timeout_seconds: 300
  
  # Notification settings
  notifications:
    email: false
    slack: false
    console: true
  
  # Reporting settings
  reporting:
    generate_reports: true
    save_history: true
    max_history_days: 30

# Task Dependencies
task_dependencies:
  check_project_health:
    - validate_specs
  
  run_tests:
    - check_project_health
  
  update_documentation:
    - run_tests
  
  comprehensive_qa:
    - run_tests
    - update_documentation
  
  performance_analysis:
    - run_tests
  
  security_audit:
    - run_tests

# Task Configuration
task_config:
  check_project_health:
    timeout: 60
    retries: 2
    critical: true
  
  run_tests:
    timeout: 300
    retries: 1
    critical: true
  
  update_documentation:
    timeout: 120
    retries: 2
    critical: false
  
  validate_specs:
    timeout: 60
    retries: 1
    critical: true
  
  comprehensive_qa:
    timeout: 600
    retries: 1
    critical: true
  
  performance_analysis:
    timeout: 300
    retries: 1
    critical: false
  
  security_audit:
    timeout: 180
    retries: 1
    critical: true

# Environment Settings
environment:
  # Development environment
  development:
    run_tests: true
    generate_reports: true
    save_history: true
  
  # CI/CD environment
  ci_cd:
    run_tests: true
    generate_reports: true
    save_history: false
    fail_fast: true
  
  # Production environment
  production:
    run_tests: false
    generate_reports: false
    save_history: false

# Integration Settings
integrations:
  # MCP Server Integration
  mcp_servers:
    byterover:
      enabled: true
      knowledge_retrieval: true
      knowledge_storage: true
    
    testsprite:
      enabled: true
      automated_testing: true
      test_plan_generation: true
    
    context7:
      enabled: true
      library_docs: true
      api_reference: true
    
    browser_tools:
      enabled: true
      quality_audits: true
      performance_monitoring: true
    
    dart:
      enabled: true
      task_management: true
      documentation_management: true
  
  # External Tools
  external_tools:
    git:
      enabled: true
      auto_commit: false
      branch_protection: true
    
    github:
      enabled: true
      issue_tracking: true
      pr_automation: false
    
    pypi:
      enabled: false
      auto_publish: false

# Monitoring and Alerting
monitoring:
  # Health monitoring
  health_checks:
    project_structure: true
    code_quality: true
    test_coverage: true
    documentation: true
    dependencies: true
  
  # Performance monitoring
  performance:
    document_generation_time: true
    cli_response_time: true
    memory_usage: true
    cpu_usage: false
  
  # Alert thresholds
  alerts:
    test_coverage_below: 80
    performance_above: 5  # seconds
    security_score_below: 90
    code_quality_below: 85

# Backup and Recovery
backup:
  # Backup settings
  enabled: true
  frequency: daily
  retention_days: 30
  
  # Backup locations
  locations:
    - assets/reports/
    - assets/config/
    - assets/specs/
  
  # Backup exclusions
  exclusions:
    - __pycache__/
    - *.pyc
    - .git/
    - venv/
    - node_modules/

# Maintenance
maintenance:
  # Cleanup tasks
  cleanup:
    temp_files: true
    old_reports: true
    cache_files: true
    log_files: true
  
  # Cleanup frequency
  frequency: weekly
  
  # Cleanup retention
  retention:
    reports: 30  # days
    logs: 7      # days
    cache: 1     # day
    temp: 1      # day